name: Build and Release

on:
  release:
    types: [published]

jobs:
  build-and-release:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Build
        run: npm run build

      - name: Create archive
        run: |
          tar -czf nas-fronted-${{ github.event.release.tag_name }}.tar.gz \
            .next \
            package.json \
            package-lock.json \
            next.config.js \
            public \
            .env.production

      - name: Upload Release Asset
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ github.event.release.upload_url }}
          asset_path: ./nas-fronted-${{ github.event.release.tag_name }}.tar.gz
          asset_name: nas-fronted-${{ github.event.release.tag_name }}.tar.gz
          asset_content_type: application/gzip